#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < fix-realpath.patch

meson \
	--prefix=/usr \
	--sysconfdir=/etc \
	--mandir=/usr/share/man \
	--localstatedir=/var \
	--sbindir=bin \
	--buildtype=plain \
	-Db_lto=false \
	-Duseroot=false \
	-Dexamples=false \
	. output

ninja -C output
ninja -C output	install

chmod u+s "$1/usr/bin/fusermount3"
rm -rf "$1/etc/init.d/"
