#!/bin/sh -e

./configure \
    --build=x86_64-pc-linux-musl \
    --host=x86_64-pc-linux-musl \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info

make
make DESTDIR="$1" install
