#!/bin/sh -e

libtoolize --force && \
aclocal && \
autoconf && \
automake \
    --add-missing \
    --gnu

patch -p1 < remove-intltool.patch

rm -rf po

# false positive
# shellcheck disable=2016
sed -i 's@LC_ALL=C $(INTLTOOL_MERGE) -x -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po@cp@g' plugins/plot_*/Makefile.am
sed -i 's/@INTLTOOL_XML_RULE@/plugin.xml : plugin.xml.in ; cp $< $@/g' plugins/*/Makefile.am

kiss l gobject-introspection && gi=en

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-gtk-doc \
    --without-lasem \
    --with-gtk \
    --with-config-backend=gsettings \
    --disable-static \
    --"${gi:-dis}"able-introspection

make
make DESTDIR="$1" install

# no static files
find "$1" -name '*.la' -exec rm -rf {} +

# no gtk-doc
rm -rf "$1/usr/share/gtk-doc"
