#!/bin/sh -e

export DESTDIR="$1"

# fixup version as they are never correct
sed -E "s|(GOOGLETEST_VERSION) [0-9\\.]+|\\1 $2|" -i CMakeLists.txt

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_SHARED_LIBS=ON \
    -DPYTHON_EXECUTABLE=python3 \
    -Dgmock_build_tests=OFF \
    -Dgtest_build_tests=OFF

cmake --build   build
cmake --install build

find "$1" -type f -name "*.pump" -exec rm -rf {} +
