#!/bin/sh -e

export RUSTFLAGS="$RUSTFLAGS -C debuginfo=2"

kiss l gobject-introspection && gi=en

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib/librsvg \
    --disable-static \
    --enable-pixbuf-loader \
    --disable-vala \
    --"${gi:-dis}"able-introspection

make
make DESTDIR="$1" install
