#!/bin/sh -e

patch -p1 -i xdg-utils-1.1.3-xdg-open-pcmanfm.patch

export ac_cv_path_XMLTO="$(type -P xmlto) --skip-validation"

autoreconf

./configure \
    --prefix=/usr

make -C scripts scripts-clean
make DESTDIR="$1" install
