#!/bin/sh -e

patch -p1 -i xdg-utils-1.1.3-xdg-open-pcmanfm.patch

ac_cv_path_XMLTO="--skip-validation"
export ac_cv_path_XMLTO

autoreconf

./configure \
    --prefix=/usr

make -C scripts scripts-clean
make DESTDIR="$1" install
