#!/bin/sh -e

patch -p1 < 001-sysmalloc.patch

./configure \
    --prefix=/usr \
    --build=x86_64-pc-linux-musl \
    --host=x86_64-pc-linux-musl \
    --sysconfdir=/etc \
    --bindir=/usr/bin \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --disable-rpath
make
make DESTDIR="$1" install
