#!/bin/sh -e

export GOPATH="$PWD/go"
export GO111MODULE=on

go build \
    -trimpath \
    -ldflags "\
        -X github.com/cli/cli/command.Version=v$2 \
        -X github.com/cli/cli/command.BuildDate=$(date +%Y-%m-%d)" \
    -o bin/gh \
    ./cmd/gh

install -Dm755 bin/gh "$1/usr/bin/gh"
