#!/bin/sh -e

export DESTDIR="$1"

sed -i '/pthread_detach/d' src/base/thread.cpp

git submodule update --init --recursive

mkdir build && cd build
cmake \
  -DUSE_SHARED_CURL=ON \
  -DUSE_SHARED_ZLIB=ON \
  -DUSE_SHARED_JPEGLIB=ON \
  -DUSE_SHARED_LIBPNG=ON \
  -DUSE_SHARED_LIBWEBP=ON \
  -DUSE_SHARED_PIXMAN=ON \
  -DUSE_SHARED_FREETYPE=ON \
  -DUSE_SHARED_GIFLIB=ON \
  -G Ninja ..

ninja -C ./ libresprite
ninja -C ./ install
