#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --enable-stats \
    --disable-wxwidgets \
    --disable-qt

make
make DESTDIR="$1" install
