#!/bin/sh -e

export GOPATH="/tmp/go"
export GOBIN="$1/usr/bin"

make build \
    VERSION=2.0.2-kiss \
    HASH=c51f84955e5fe924c34b4f7e06d17cd8731022cf
make build \
    VERSION=2.0.2-kiss \
    HASH=c51f84955e5fe924c34b4f7e06d17cd8731022cf \
    install
