#!/bin/sh -e

# -DENABLE_UNSTABLE_API_ABI_HEADERS=ON
# Installs some old Xpdf headers required by certain programs (e.g. Inkscape)

cmake . \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DENABLE_UNSTABLE_API_ABI_HEADERS=ON \
    -DENABLE_CPP=ON \
    -DENABLE_QT5=OFF \
    -DWITH_NSS3=OFF

make
make DESTDIR="$1" install
