#!/bin/sh -e

export DESTDIR="$1"
export ac_cv_prog_RUBY=no

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=plain \
    -Dwith-sdl=no \
    -Denable-docs=no \
    -Denable-glibtest=no \
    -Denable-nls=no \
    -Denable-introspection=no \
    -Dwith-vala=no \
    -Dwith-lua=no \
    -Dwith-libavformat=no \
    -Denable-silent-rules=no \
    . output

ninja -C output
ninja -C output install
