#!/bin/sh -e

_plug="${0##*abiword-plugin-}"
_plug="${_plug%%/build}"

./configure \
    --prefix=/usr \
    --disable-maintainer-mode \
    --disable-static \
    --disable-default-plugins \
    --disable-builtin-plugins \
    --disable-collab-backend-telepathy \
    --enable-clipart \
    --enable-statusbar \
    --enable-templates \
    --with-gio \
    --without-gnomevfs \
    --without-gtk2 \
    --disable-debug \
    --with-goffice \
    --without-libical \
    --enable-print \
    --disable-collab-backend-xmpp \
    --disable-collab-backend-tcp \
    --disable-collab-backend-service \
    --without-evolution-data-server \
    --disable-introspection \
    --without-champlain \
    --without-redland \
    --disable-spell \
    --enable-plugins="$_plug"

make

(
    cd "plugins/$_plug"
    make DESTDIR="$1" install
)

# no static files
find "$1" -name '*.la' -exec rm -rf {} +
