#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
	--libexecdir=/usr/lib/upower \
	--localstatedir=/var \
    --enable-deprecated \
    --disable-static \
	--disable-nls

make
make DESTDIR="$1" install
