#!/bin/sh -e

export DESTDIR="$1"

cd "AppStream-$2"

patch -p1 < ../no-gtk-doc.patch

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=plain \
    -Dqt=false \
    -Dmaintainer=false \
    -Ddocs=false \
    -Dapidocs=false \
    -Dinstall-docs=false \
    -Dstemming=false \
    -Dvapi=true \
    -Dapt-support=false \
    -Dgir=true \
    . output

ninja -C output
ninja -C output install

# Remove unused stuff
rm -rf "$1/usr/share/gettext"
