#!/bin/sh -e

export MSGFMT=/usr/bin/true
export MSGCAT=/usr/bin/true
export MSGMERGE=/usr/bin/true
export XGETTEXT=/usr/bin/true
export INTLTOOL_PERL=/usr/bin/true

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

rm -rf po
rm -rf po-functions

# false positive
# shellcheck disable=2016
sed -i 's@LC_ALL=C $(INTLTOOL_MERGE) -x -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po@cp@g' plugins/fn-*/Makefile.*
sed -i 's/@INTLTOOL_XML_NOMERGE_RULE@/%xml : %xml.in ; cp $< $@/g' schemas/Makefile.*
sed -i 's/@INTLTOOL_XML_RULE@/%xml : %xml.in ; cp $< $@/g' plugins/*/Makefile.*
sed -i 's/@INTLTOOL_XML_RULE@/%xml : %xml.in ; cp $< $@/g' component/Makefile.*
sed -i '/@YELP_HELP_RULES@/d' doc/Makefile.*
sed -i 's/_//g' schemas/*.xml*

kiss l gobject-introspection && gi=en

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-gtk-doc \
    --disable-maintainer-mode \
    --disable-static \
    --without-psiconv \
    --without-python \
    --with-zlib \
    --without-gda \
    --"${gi:-dis}"able-introspection \
    --without-perl \
    --disable-nls

make
make DESTDIR="$1" install

rm -rf "$1/etc/gconf"

# no static files
find "$1" -name '*.la' -exec rm -rf {} +

# no help files
rm -rf "$1/usr/share/help"
