#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DEXIV2_BUILD_SAMPLES=OFF \
    -DFLAG=1

cmake --build   build
cmake --install build
