#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=plain \
    -Dalsa=enabled \
    -Dintrospection=enabled \
    -Dpackage-origin="https://k1ss.org" \
    -Dpackage-name="GStreamer base plug-ins (KISS Linux)" \
    . output

ninja -C output
ninja -C output install
