#!/bin/sh -e

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

# CXXFLAGS is propagated to /etc/R/Makeconf that is read when building
# additional R modules. -D__MUSL__ is needed for some modules like Rcpp.
# htps://github.com/RcppCore/Rcpp/issues/448
export CXXFLAGS="$CXXFLAGS -D__MUSL__"

rm -rf po

./configure \
	--prefix=/usr \
    --sysconfdir=/etc/R \
	--localstatedir=/var \
	--mandir=/usr/share/man \
	--libdir=/usr/lib \
	rdocdir=/usr/share/doc/R \
	rincludedir=/usr/include/R \
	rsharedir=/usr/share/R \
	--disable-nls \
	--enable-R-shlib \
	--disable-java \
	--without-recommended-packages \
	--with-blas=openblas \
	--with-cairo \
	--with-ICU \
	--with-jpeglib \
	--with-lapack \
	--with-libpng \
	--with-libtiff \
	--with-tcltk \
	--with-x

make -j1
make DESTDIR="$1" install
# Install libRmath.so.
make -j1 -C src/nmath/standalone
make DESTDIR="$1" -C src/nmath/standalone install

# Fixup R wrapper script (taken from Arch).
rm "$1/usr/lib/R/bin/R"
ln -sf /usr/bin/R "$1/usr/lib/R/bin/R"

# Remove some useless files (COPYING is duplicated, it will be
# in -doc, don't worry).
rm "$1/usr/lib/R/COPYING" "$1/usr/lib/R/SVN-REVISION"

mkdir -p "$1/etc/R"

# R apparently ignores --sysconfdir, so we must manually move configs
# to /etc/R and make symlinks.
cd "$1/usr/lib/R/etc"
for f in *; do
	mv "$f" "$1/etc/R" && ln -sf "/etc/R/$f" "$f"
done

rm -rf "$1/usr/lib/R/library/translations"
rm -rf "$1/usr/share/R/licenses"
rm -rf "$1/usr/share/doc"
