#!/bin/sh -e

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
	-DCMAKE_BUILD_TYPE=None \
	-DUSE_QT5=ON \
    -DWITH_DOC=OFF

make -C build
make -C build \
    DESTDIR="$1" \
    install
