#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

autoreconf -fis

./configure \
    --build=x86_64-pc-linux-musl \
    --host=x86_64-pc-linux-musl \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --without-fontconfig \
    --disable-werror

make
make DESTDIR="$1" PREFIX="$1" install
