#!/bin/sh -e

CXXFLAGS="$CXXFLAGS -Wno-error=implicit-fallthrough -Wno-error=parentheses" \
./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --localstatedir=/var \
    --disable-dependency-tracking \
    --enable-fast-install

make
make DESTDIR="$1" install
