#!/bin/sh -e

UDEV_RULES_PATH=/usr/lib/udev/rules.d MOUNT_FUSE_PATH=/usr/bin \
	./configure \
		--prefix=/usr \
		--libdir=/usr/lib \
		--enable-lib \
		--disable-example

make
make DESTDIR="$1" install

# we don't use sysvrc
rm -r "$1/etc/init.d"

# udev handles these
rm -r "$1/dev"
