#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --localstatedir=/var \
    --disable-bdjava-jar \
    --without-libxml2 \
    --without-freetype \
    --disable-static

make
make DESTDIR="$1" install
