#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --localstatedir=/var \
    --disable-xaw8 \
    --disable-static \
    --disable-xaw6

make
make DESTDIR="$1" install
