#!/bin/sh -e

export CFLAGS="$CFLAGS -w"
export API="sdl2"

cp -R grafx2/recoil grafx2/3rdparty/recoil-5.0.0
touch grafx2/3rdparty/recoil-5.0.0/.ok

sed -i 's/defined(__macosx__)/!defined(__GLIBC__)/' grafx2/src/init.c

make -C grafx2/src
make -C grafx2/src \
	PREFIX=/usr \
	DESTDIR="$1" \
	install
