#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX:PATH='/usr' \
    -DCMAKE_SKIP_RPATH:BOOL='YES' \
    -Dbuild_tools:BOOL='ON' \
    -Dpython-bindings:BOOL='OFF' \
    -Dboost-python-module-name='python' \
    -DPYTHON_EXECUTABLE:FILEPATH="/usr/bin/python" \
    -DPYTHON_INCLUDE_DIR:PATH="/usr/include/python" \
    -DPYTHON_LIBRARY:FILEPATH="/usr/lib/libpython3.8.so" \
    -Wno-dev

make -C build
make -C build DESTDIR="$1" install
