#!/bin/sh -e

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

./configure \
    --prefix=/usr \
    --libexecdir=/usr/bin \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --disable-altivec \
    --disable-static \
    --disable-python \
    --disable-alsatest \
    --disable-nls \
    --disable-silent-rules \
    --disable-glibtest \
    --without-webkit \
    --enable-mp \
    --disable-dependency-tracking \
    --enable-gimp-console \
    --without-aa \
    --disable-check-update

make -j"$(nproc)"
make DESTDIR="$1" install

rm -rf "$1/usr/share/gtk-doc"
