#!/bin/sh -e

sed -i "s/if \`\$INTLTOOL_PERL -e/if test -z \`\$INTLTOOL_PERL -e/g" configure
sed -i "s/if test \"x\$have_required_xgettext\" \= \"xno\"; then/if test -z \"x\$have_required_xgettext\" \= \"xno\"; then/g" configure

./configure -C \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --disable-altivec \
    --disable-python \
    --disable-alsatest \
    --disable-nls \
    --disable-silent-rules \
    --disable-glibtest \
    --without-webkit \
    --enable-mp \
    --disable-dependency-tracking \
    --enable-gimp-console \
    --without-aa \
    --disable-check-update

for i in po po-plug-ins po-python po-libgimp po-script-fu po-tips; do
    printf 'all:\n\ttrue\ninstall:\n\ttrue\nclean:\n\ttrue\n' > "$i/Makefile"
done

make -j"$(nproc)"
make DESTDIR="$1" install
