#!/bin/sh -e

./configure \
    --prefix=/usr \
    --datadir=/usr/share \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --localstatedir=/var

make
make \
    DESTDIR="$1" \
    pkgconfigdir=/usr/lib/pkgconfig \
    install
